version: "3.1"
services:
    docker-mysql:
        container_name: authentication_db
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: auth_server
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    docker-redis-cluster:
        container_name: authentication_redis
        image: grokzen/redis-cluster
        networks:
            - default
    authentication-server:
        container_name: authentication_app
        build:
            context: ./
        ports:
            - "9590:3000"
        environment:
           DB_HOST: authentication_db
           DB_NAME: auth_server
           DB_PORT: 3306
           DB_USER: root
           DB_PASSWORD: 123456
           REDIS_HOST: authentication_redis
        links:
            - docker-mysql
            - docker-redis-cluster
        depends_on:
            - docker-mysql
            - docker-redis-cluster
        networks:
            - default
volumes:
    persistent:
